### ISSUE TITLE
Unable to img build with v0.4.2

### ISSUE THREAD

**Issue by glerchundi** [genuinetools/img#114]
I upgraded from 0.3.4 to 0.4.2 and `img build` stopped working.

Building with `img-in-docker` using the following versions:

```
FROM golang:1.10.2-alpine3.7

# runc - CLI tool for spawning and running containers according to the OCI specification
RUN curl -o /usr/local/bin/runc -L https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 \
&& chmod 755 /usr/local/bin/runc

# img - a standalone, daemon-less, unprivileged Dockerfile and OCI compatible container image builder.
ENV IMG_DISABLE_EMBEDDED_RUNC 1
RUN curl -o /usr/local/bin/img -L https://github.com/genuinetools/img/releases/download/v0.4.2/img-linux-amd64 \
&& chmod 755 /usr/local/bin/img
```

When I try to do an `img build` it fails with this error: `time="2018-06-05T05:22:44Z" level=fatal msg="please install 'runc'"`. This seems to be related to the relatively new change of embedding the `runc` inside the `img`.

I also tried by removing the `IMG_DISABLE_EMBEDDED_RUNC` envar but now i'm facing a different and probably unrelated error, which seems to be a bug?

```
[copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer]: panic: failed to copy /src-0/mycontainer-linux-amd64 to usr/local/bin/mycontainer: failed to copy files: copy file range failed: operation not permitted
 
 goroutine 1 [running]:
 main.main()
 	/go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
 failed to solve: executor failed running [copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer]: exit code 2
```

As the error states it is failing [here](https://github.com/tonistiigi/copy/blob/ebb275123e336189fbcb23fb05e1424319aa3796/cmd/copy/main.go#L57) which is probably because [this change was made](https://github.com/tonistiigi/copy/commit/4c898222b335fa5c331de180746487855d27bb3b).

I tried to track this down in order to identify where it is being used with no success. I didn't find any reference in `img`, `runc` or `buildkit`. I'm sorry for not being able to give more details.

Thanks again,

**Comment by AkihiroSuda** [comment]
Could you provide distro info?

* Did you add subids to /etc/sub[ug]id?
* Some distros require `echo 1 > /proc/sys/kernel/unprivileged_userns_clone`

**Comment by glerchundi** [comment]
Thanks for the quick response, you really rock!

> Did you add subids to /etc/sub[ug]id?

Nope! Should I? They are empty:

```
bash-4.4# ls -l /etc/sub[gu]id
-rw-r--r--    1 root     root             0 Nov 29  2017 /etc/subgid
-rw-r--r--    1 root     root             0 Nov 29  2017 /etc/subuid
```

> Some distros require echo 1 > /proc/sys/kernel/unprivileged_userns_clone
 
Umm, I cannot append anything in `/proc`

```
bash-4.4# id
uid=0(root) gid=0(root)
bash-4.4# echo 1 > /proc/sys/kernel/unprivileged_userns_clone
bash: /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
bash-4.4# ls -l /proc/sys/kernel/unprivileged*
-rw-r--r--    1 root     root             0 Jun  5 05:55 /proc/sys/kernel/unprivileged_bpf_disabled
bash-4.4# mount | grep proc
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
```

Thanks!

**Comment by AkihiroSuda** [comment]
Yes, e.g. `user:100000:65536` is needed.

Probably we should also allow "single user mode" although it is unlikely to work with `apt`, but it would require some hack for containerd snapshotter subsystem.

**Comment by glerchundi** [comment]
Docker is running as root and with `--privileged` turned on. I appended what you suggested to both `/etc/sub[ug]id` but nothing changed.

I also tried to change the `/proc` param by using `sysctl` but it didn't work:

```
bash-4.4# sysctl kernel.unprivileged_userns_clone 1
sysctl: error: 'kernel.unprivileged_userns_clone' is an unknown key
```

**Comment by AkihiroSuda** [comment]
Are you running img as the root in Docker or as an unprivileged `USER`?
Could you provide dockerfile and `uname -a`?

**Comment by glerchundi** [comment]
> Are you running img as the root in Docker or as an unprivileged USER?

As root, no user statements neither in `Dockerfile` nor in `docker` execution.



> Could you provide dockerfile and uname -a?

```
bash-4.4# uname -a
Linux 7746d7ab5c01 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux
bash-4.4# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

`Dockerfile.build`:

```
FROM golang:1.10.2-alpine3.7

ENV OS linux
ENV PKGPATH github.com/mycompany/mycontainer
ENV CGO_ENABLED 0

# copy current workspace
COPY . ${GOPATH}/src/${PKGPATH}

# minimal needed packages
RUN apk add --update --no-cache curl bash git make mariadb mariadb-client shadow-uidmap

# runc - CLI tool for spawning and running containers according to the OCI specification
RUN curl -o /usr/local/bin/runc -L https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64 \
&& chmod 755 /usr/local/bin/runc

# img - a standalone, daemon-less, unprivileged Dockerfile and OCI compatible container image builder.
ENV IMG_DISABLE_EMBEDDED_RUNC 1
RUN curl -o /usr/local/bin/img -L https://github.com/genuinetools/img/releases/download/v0.4.2/img-linux-amd64 \
&& chmod 755 /usr/local/bin/img
```

`Dockerfile`:
```
FROM alpine:3.7

# s6, tar and ca-certificates (updating them)
RUN apk add --update --no-cache ca-certificates curl s6 s6-portable-utils && update-ca-certificates

# s6 overlay (without binaries)
RUN wget -O /s6-overlay.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-nobin.tar.gz 
RUN gunzip -c /s6-overlay.tar.gz | tar -xf - -C /

# Make port 8080 available to the world outside this container
EXPOSE 8080

# mycontainer
RUN adduser -S mycontainer
ADD mycontainer-linux-amd64 /usr/local/bin/mycontainer
RUN s6-envuidgid mycontainer s6-chown -U /usr/local/bin/mycontainer && s6-chmod 0755 /usr/local/bin/mycontainer

# default entrypoint, drop privileges
ENTRYPOINT [ "/init", "with-contenv", "s6-setuidgid", "mycontainer" ]

CMD ["mycontainer"]
```

Thanks!

**Comment by AkihiroSuda** [comment]
* runc rc5 SHOULD work for rootful mode but not tested with img. I suggest using the latest one or the embedded runc.
* Does `ENV IMG_DO_UNSHARE=1` or `ENV IMG_RUNNING_TESTS=1` work?

**Comment by glerchundi** [comment]
First of all, thanks for this speedy support.

It didn't work, although I must say I'm blindly doing everything without knowing really what i'm doing! So probably i'm doing lots of mistakes.

```
bash-4.4# img build -t mycontainer:1.2.3 .
FATA[0000] please install `runc`                        
bash-4.4# unset IMG_DISABLE_EMBEDDED_RUNC
bash-4.4# img version
img:
 version     : v0.4.2
 git hash    : 83e14d3
 go version  : go1.10.1
 go compiler : gc
 platform    : linux/amd64
bash-4.4# img build -t mycontainer:1.2.3 .
...
 > copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer:
panic: failed to copy /src-0/mycontainer-linux-amd64 to usr/local/bin/mycontainer: failed to copy files: copy file range failed: operation not permitted

goroutine 1 [running]:
main.main()
	/go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
------
failed to solve: executor failed running [copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer]: exit code 2
bash-4.4# rm -fr /tmp/img*
bash-4.4# export IMG_DO_UNSHARE=1
bash-4.4# img build -t mycontainer:1.2.3 .
nsenter: USER is unset: No such file or directory
bash-4.4# export USER=root
bash-4.4# img build -t mycontainer:1.2.3 .
...
 > copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer:
panic: failed to copy /src-0/mycontainer-linux-amd64 to usr/local/bin/mycontainer: failed to copy files: copy file range failed: operation not permitted

goroutine 1 [running]:
main.main()
	/go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
------
failed to solve: executor failed running [copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer]: exit code 2
bash-4.4# export IMG_RUNNING_TESTS=1
bash-4.4# img build -t mycontainer:1.2.3 .
...
 > copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer:
panic: failed to copy /src-0/mycontainer-linux-amd64 to usr/local/bin/mycontainer: failed to copy files: copy file range failed: operation not permitted

goroutine 1 [running]:
main.main()
	/go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
------
failed to solve: executor failed running [copy --unpack /src-0/mycontainer-linux-amd64 usr/local/bin/mycontainer]: exit code 2
```

**Comment by AkihiroSuda** [comment]
Could you try whether vanilla buildkit works?

**Comment by glerchundi** [comment]
Sorry @AkihiroSuda but I don't have much time to invest on this, thanks for your supportive attitude. I'll stick with 0.3.4 until I find a free slot to make further investigation.

Feel free to close this issue, thanks.

**Comment by jessfraz** [comment]
sorry about this I will try to recreate

**Comment by glerchundi** [comment]
> sorry about this I will try to recreate

Thanks for your time, If it's possible let me know when you come up with something.

**Comment by BenHall** [comment]
I was trying to use this on Katacoda (https://www.katacoda.com/courses/ubuntu/playground) but hitting a similar issue. 0.3.9 is OK

```
> copy --unpack /src-0 app/:
panic: failed to copy /src-0/. to app/: failed to copy files: copy file range failed: operation not permitted

goroutine 1 [running]:
main.main()
        /go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2b1
```

**Comment by arunmk** [comment]
I hit the same issue with a tiny dockerfile:

```
FROM ubuntu:16.04
RUN mkdir -p /home/test
COPY files/* /home/test
CMD ["/bin/bash"]

```
I get the following error:
```
 => => unpacking docker.io/tonistiigi/copy:v0.1.3@sha256:87c46e7b413cdd2c2702902b481b390ce263ac9d942253d366f3b1a3c16f96d6                                                                                                                0.0s
 => local://context                                                                                                                                                                                                                      0.0s
 => => transferring context: 216B                                                                                                                                                                                                        0.0s
 => CACHED /bin/sh -c mkdir -p /home/test                                                                                                                                                                                                0.0s
 => ERROR copy /src-0/* home/test                                                                                                                                                                                                        0.1s
------
 > copy /src-0/* home/cdsw:
#7 0.087 panic: failed to copy /src-0/* to home/cdsw: failed to copy files: copy file range failed: operation not permitted
```

The version I use is:
```
# /img-linux-amd64 version
img:
 version     : v0.4.6
 git hash    : 9c9f6f6
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
```

Could someone please help me with workarounds for this case?

**Comment by arunmk** [comment]
Is there a host kernel version requirement to have copy_file_range to run img 0.4.6 in a docker container? My host kernel is at 3.10.0-693.5.2.el7.x86_64 (CentOS Linux release 7.4.1708 (Core))

**Comment by danlenar** [comment]
The embedded runc in img was causing "the copy file range failed: operation not permitted" on CentOS 7.

I am using img 0.4.6
```
img:
 version     : v0.4.6
 git hash    : 9c9f6f6
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
```

I was able to symlink the runc that is packaged with docker-ce 18.05-ce to get around the problem and to be able to finally build an image that contained COPY in the Dockerfile.

`sudo ln -s /usr/bin/docker-runc /usr/bin/runc`

The runc version I am using
```
docker-runc --version
runc version 1.0.0-rc5
commit: 4fc53a81fb7c994640722ac585fa9ca548971871
spec: 1.0.0
```

The embedded runc that was causing me issues
```
/tmp/img-runc033549591/runc --version
runc version 1.0.0-rc5+dev
commit: dd56ece8236d6d9e5bed4ea0c31fe53c7b873ff4
spec: 1.0.0
```

**Comment by arunmk** [comment]
Thanks @danlenar! That did the job for me!

**Comment by arunmk** [comment]
@danlenar I did not get it to work with vanilla runc v1.0.0-rc5 but docker-runc v1.0.0-rc5 worked. Looking at the build in docker-ce (https://github.com/docker/docker-ce/blob/57b10679e667c8c20c0989fc75000b075a452cb6/components/engine/hack/dockerfile/install/runc.installer), it looks like the key difference is `RUNC_BUILDTAGS="${RUNC_BUILDTAGS:-"seccomp apparmor selinux"}"`

Is my understanding correct?

**Comment by danlenar** [comment]
@arunmk 

The vanilla runc is missing commit line in the version output, which is causing img to default to still using embedded runc.

```
./runc.amd64 --version
runc version 1.0.0-rc5
spec: 1.0.0
```

The code (https://github.com/containerd/go-runc/blob/14606eb66abd9e834e3bd22a4f5f46a3aad54c54/runc.go#L609-L612) expects there to be 3 lines in the runc version output.

**Comment by arunmk** [comment]
@danlenar thanks, this clears it up now.

**Comment by arunmk** [comment]
Just to close on this thread, I took the source code of vanilla runc (tag `v1.0.0-rc5`), compiled it and used this with the img and my dockerfiles worked.
